### ISSUE TITLE
Subscriptions not reflected to database after creation

### ISSUE THREAD

**Issue by fwartner** [kanuu-io/kanuu-laravel#3]
After I created a subscription during the process (redirecting to kanuu, paddle and so on..) thee subscription won't show up in the database.

**Comment by lorisleiva** [comment]
Hi Florian, thanks for raising this.

Did you generate the whole thing via the new `kanuu:publish` command or is the codebase from before?

Are you trying with some real Paddle modals on Kanuu or are you testing this with the Paddle webhook simulator? In case you’re using the latter you have to add `{“kanuu”:”your_identifier”}` to the `passthrough` attribute for it to match your billable entity.

**Comment by fwartner** [comment]
Hey,

well.. The webhook-simulator gives me the following:

```
Error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

The server is provisioned by Laravel Forge.
When running the app on Vapor, it seems to work. But due to some regulations on the runtime I cannot run my app on vapor..

**Comment by slashequip** [comment]
Hey @fwartner, this sounds like an issue with Nginx, we had some similar sounding issues where webhooks were not reaching the application (at all).

We adjusted our Nginx config in Forge as so (and restarted Nginx);

```
ssl_protocols SSLv2 SSLv3 TLSv1 TLSv1.2 TLSv1.3;
ssl_ciphers 'TLS-RSA-WITH-AES-256-CBC-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
```

This enables SSL v3 and adds the ciphers required by Paddle, see: https://developer.paddle.com/webhook-reference/webhooks-security

Once that is done let us know if you are still having issues with the package itself.
